class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.12.16.tar.gz"
  sha256 "a63a5bb76bc2451dc60f5c50c7f1d8209c016e474c63c9acce412aee47fce2c7"
  license any_of: ["Apache-2.0", "MIT"]
  compatibility_version 1
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    root_url "https://github.com/SharkyRawr/homebrew-uv/releases/download/bottles-0.12.16"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:  "ca2f9397f2cba68f07694c9ccbc3827d893f221a2a75c1974f4a6560f18d8a6d"
    sha256 cellar: :any,                 x86_64_linux: "9da82565b8dad9a70789c822d2d12eda02d605cb29857f690c5f570f91386a06"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  # downloads crates on install and wheels in test
  deny_network_access! :postinstall

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
